//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributos
    {
        public int AtributoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int TipoEquipamentoId { get; set; }
    
        public virtual TipoEquipamento TipoEquipamento { get; set; }
    }
}
