//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atributos()
        {
            this.Especificacoes = new HashSet<Especificacoes>();
        }
    
        public int AtributoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int TipoEquipamentoId { get; set; }
    
        public virtual TipoEquipamento TipoEquipamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especificacoes> Especificacoes { get; set; }
    }
}
