//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shield01Entities : DbContext
    {
        public shield01Entities()
            : base("name=shield01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acessos> Acessos { get; set; }
        public virtual DbSet<Atributos> Atributos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Equipamentos> Equipamentos { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<EspecificacaoEquipamento> EspecificacaoEquipamento { get; set; }
        public virtual DbSet<Especificacoes> Especificacoes { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Manutencao> Manutencao { get; set; }
        public virtual DbSet<OrdemServico> OrdemServico { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Prioridade> Prioridade { get; set; }
        public virtual DbSet<Sidebar> Sidebar { get; set; }
        public virtual DbSet<SoftwareEquipemento> SoftwareEquipemento { get; set; }
        public virtual DbSet<Softwares> Softwares { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tarefa> Tarefa { get; set; }
        public virtual DbSet<TipoEquipamento> TipoEquipamento { get; set; }
        public virtual DbSet<TipoSolicitacao> TipoSolicitacao { get; set; }
        public virtual DbSet<Transferencia> Transferencia { get; set; }
    }
}
