//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shield01Entities : DbContext
    {
        public shield01Entities()
            : base("name=shield01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acessos> Acessos { get; set; }
        public virtual DbSet<Atributos> Atributos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<EmailConfig> EmailConfig { get; set; }
        public virtual DbSet<Equipamentos> Equipamentos { get; set; }
        public virtual DbSet<Equipe> Equipe { get; set; }
        public virtual DbSet<EspecificacaoEquipamento> EspecificacaoEquipamento { get; set; }
        public virtual DbSet<Especificacoes> Especificacoes { get; set; }
        public virtual DbSet<Licencas> Licencas { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<OrdemServico> OrdemServico { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Prioridade> Prioridade { get; set; }
        public virtual DbSet<Sidebar> Sidebar { get; set; }
        public virtual DbSet<SoftwareEquipemento> SoftwareEquipemento { get; set; }
        public virtual DbSet<Softwares> Softwares { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tarefa> Tarefa { get; set; }
        public virtual DbSet<TipoEquipamento> TipoEquipamento { get; set; }
        public virtual DbSet<TipoSolicitacao> TipoSolicitacao { get; set; }
        public virtual DbSet<Transferencia> Transferencia { get; set; }
        public virtual DbSet<vw_equipe_ordemServico> vw_equipe_ordemServico { get; set; }
        public virtual DbSet<vw_tarefas_status_dados> vw_tarefas_status_dados { get; set; }
        public virtual DbSet<vw_equipamentos_manutencao_por_mes> vw_equipamentos_manutencao_por_mes { get; set; }
        public virtual DbSet<vw_os_encerrados_por_mes> vw_os_encerrados_por_mes { get; set; }
        public virtual DbSet<vw_quantidade_equipamentos_por_departamento> vw_quantidade_equipamentos_por_departamento { get; set; }
        public virtual DbSet<vw_quantidade_equipamentos_por_tipo> vw_quantidade_equipamentos_por_tipo { get; set; }
        public virtual DbSet<vw_tarefas_encerradas_por_mes> vw_tarefas_encerradas_por_mes { get; set; }
        public virtual DbSet<vw_os_status_dados> vw_os_status_dados { get; set; }
        public virtual DbSet<vw_dados_index_os> vw_dados_index_os { get; set; }
        public virtual DbSet<vw_colaborador_tarefas> vw_colaborador_tarefas { get; set; }
        public virtual DbSet<Manutencao> Manutencao { get; set; }
    }
}
