//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamentos
    {
        public int EquipamentoId { get; set; }
        public string Observacao { get; set; }
        public System.DateTime DataAquisicao { get; set; }
        public Nullable<System.DateTime> DataGarantia { get; set; }
        public string NumeroPatrimonial { get; set; }
        public string ServiceTagSerial { get; set; }
        public int PessoaId { get; set; }
        public int StatusId { get; set; }
        public int TipoEquipamentoId { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoEquipamento TipoEquipamento { get; set; }
    }
}
