//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipamentos()
        {
            this.EspecificacaoEquipamento = new HashSet<EspecificacaoEquipamento>();
            this.SoftwareEquipemento = new HashSet<SoftwareEquipemento>();
            this.Transferencia = new HashSet<Transferencia>();
            this.Manutencao = new HashSet<Manutencao>();
        }
    
        public int EquipamentoId { get; set; }
        public string Observacao { get; set; }
        public System.DateTime DataAquisicao { get; set; }
        public Nullable<System.DateTime> DataGarantia { get; set; }
        public string NumeroPatrimonial { get; set; }
        public string ServiceTagSerial { get; set; }
        public int PessoaId { get; set; }
        public int StatusId { get; set; }
        public int TipoEquipamentoId { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecificacaoEquipamento> EspecificacaoEquipamento { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoEquipamento TipoEquipamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareEquipemento> SoftwareEquipemento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manutencao> Manutencao { get; set; }
    }
}
