//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especificacoes
    {
        public int EspecificacaoId { get; set; }
        public string Nome { get; set; }
        public int AtributoId { get; set; }
        public int PessoaId { get; set; }
    }
}
