//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencas
    {
        public int LicencaId { get; set; }
        public int SoftwareId { get; set; }
        public int Quantidade { get; set; }
        public Nullable<double> Preco { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        public virtual Softwares Softwares { get; set; }
    }
}
