//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manutencao
    {
        public int ManutencaoId { get; set; }
        public System.DateTime DataEntrada { get; set; }
        public Nullable<System.DateTime> DataSaida { get; set; }
        public string Observacao { get; set; }
        public int EquipamentoId { get; set; }
        public string ComoEntrou { get; set; }
        public string ComoSaiu { get; set; }
    
        public virtual Equipamentos Equipamentos { get; set; }
    }
}
