//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.Tarefa = new HashSet<Tarefa>();
        }
    
        public int OrdemServicoId { get; set; }
        public string Titulo { get; set; }
        public string ClienteNome { get; set; }
        public string ClienteEmail { get; set; }
        public Nullable<int> TipoSolicitacaoId { get; set; }
        public string Descricao { get; set; }
        public int PrioridadeId { get; set; }
        public Nullable<int> EquipeId { get; set; }
        public System.DateTime DataAbertura { get; set; }
        public Nullable<System.DateTime> DataEncerramento { get; set; }
        public int StatusId { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoSolicitacao TipoSolicitacao { get; set; }
        public virtual Prioridade Prioridade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefa> Tarefa { get; set; }
    }
}
