//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoas()
        {
            this.Equipamentos = new HashSet<Equipamentos>();
            this.Especificacoes = new HashSet<Especificacoes>();
        }
    
        public int PessoaId { get; set; }
        public string Nome_Completo { get; set; }
        public string Senha { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Telefone { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> UltimoAcesso { get; set; }
        public int AcessoId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Acessos Acessos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipamentos> Equipamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especificacoes> Especificacoes { get; set; }
        public virtual Status Status { get; set; }
    }
}
