//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sidebar
    {
        public int Id { get; set; }
        public string titulo { get; set; }
        public string icon { get; set; }
        public string action { get; set; }
        public string controller { get; set; }
        public bool tipo { get; set; }
        public int pai { get; set; }
    }
}
