//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int TarefaId { get; set; }
        public Nullable<int> OrdemServicoId { get; set; }
        public int PessoaId { get; set; }
        public int PrioridadeId { get; set; }
        public int TipoSolicitacaoId { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataEncerramento { get; set; }
        public int StatusId { get; set; }
    
        public virtual OrdemServico OrdemServico { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        public virtual Prioridade Prioridade { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoSolicitacao TipoSolicitacao { get; set; }
    }
}
