//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int TransferenciaId { get; set; }
        public int DepartamentoAtual { get; set; }
        public int DepartamentoAntigo { get; set; }
        public int EquipamentoId { get; set; }
        public int PessoaId { get; set; }
        public System.DateTime DataTransferencia { get; set; }
        public string Observacao { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Departamentos Departamentos1 { get; set; }
        public virtual Equipamentos Equipamentos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
