//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_dados_index_os
    {
        public Nullable<decimal> Produtividade { get; set; }
        public long AguardandoAtendimento { get; set; }
        public long Total { get; set; }
    }
}
