//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeEquipamentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_equipe_ordemServico
    {
        public string Equipe { get; set; }
        public string Responsavel { get; set; }
        public long OSEncerrados { get; set; }
        public long OSAbertos { get; set; }
    }
}
